#!/bin/bash
# @author   Samuel Walters-Nevet                                                                            #
# @date     Summer, 2016                                                                                    #
# @brief    Extracts an archive based upon its file extension                                               #
# @file     extract.sh                                                                                      #
#                                                                                                           #
# Note:                                                                                                     #
#   Adding a function like the one below to your bashrc file ('~/.bashrc') can make this a lot more useful: #

extract() {
    bash ~/scripts/extract.sh "$@"
}
#############################################################################################################

if [[ -z "$1" ]]; then
        # display usage if no parameters given
        echo "Usage: extract [-d] <archive>
-d  Extract files into a subdirectory"

    else
        IN_DIR=false

        if [[ "$1" = "-d" ]]; then
            IN_DIR=true;
            shift
        fi

        if [[ -f "$1" ]] ; then
            IN="$1"

            if [[ "$IN_DIR" = true ]]; then
                NAME="${1%.*}"
                mkdir "$NAME" && cd "$NAME"
                IN="../$(basename "$1")"
            fi

            case "$1" in
            *.tar.bz2) tar xvjf "$IN" ;;
            *.tar.gz) tar xvzf "$IN" ;;
            *.tar.xz) tar xvJf "$IN" ;;
            *.lzma) unlzma "$IN" ;;
            *.bz2) bunzip2 "$IN" ;;
            *.rar) unrar x -ad "$IN" ;;
            *.gz) gunzip "$IN" ;;
            *.tar) tar xvf "$IN" ;;
            *.tbz2) tar xvjf "$IN" ;;
            *.tgz) tar xvzf "$IN" ;;
            *.zip) unzip "$IN" ;;
            *.Z) uncompress "$IN" ;;
            *.7z) 7z x "$IN" ;;
            *.xz) unxz "$IN" ;;
            *.exe) cabextract "$IN" ;;
            *) echo "extract: '$1' - unknown archive method" ;;
            esac
        else
            echo "$1 - file does not exist"
        fi
    fi
}
