#!/bin/bash
# @author   Samuel Walters-Nevet                                                                            #
# @date     Summer, 2016; updated Spring 2017                                                               #
# @brief    Extracts an archive based upon its file extension                                               #
# @file     extract.sh                                                                                      #
#                                                                                                           #
# Note:                                                                                                     #
#   Adding a function like the one below to your bashrc file ('~/.bashrc') can make this a lot more useful: #
#                                                                                                           #
# Prerequisits:                                                                                             #
#   sudo apt install tar xz-utils bzip2 unrar gzip unzip p7zip cabextract                                   #
#                                                                                                           #
extract() {
    bash ~/scripts/extract.sh "$@"
}
#############################################################################################################

autoincr() {
    f="$1"
    ext=""
    [[ "$f" == *.* ]] && ext=".${f##*.}"

    if [[ -e "$f" ]] ; then
        i=1
        f="${f%.*}";

        while [[ -e "${f}_${i}${ext}" ]]; do
            let i++
        done

        f="${f}_${i}${ext}"
    fi
    echo "$f"
}

for f in "$@"; do
    if [[ -z "$f" ]]; then
        # display usage if no parameters given
        echo "Usage: extract <archive>"
        exit 1;
    elif [[ -z "$f" ]]; then
        # display usage if no parameters given
        echo "$f - file does not exist"
        exit 2;
    fi

    FILE="$f"

    DIR="${FILE%.*}"

    if [[ "$DIR" == *.part[[:digit:]]* ]]; then
        PART="${DIR##*.part}"
        PART="${PART%.*}"

        if [ "$PART" -eq "$PART" ] 2>/dev/null; then
            DIR="${DIR%.part*}"
        fi
    fi

    while [[ -e "$DIR" ]]; do
        DIR="$(autoincr "$DIR")"
    done

    FILE="$(pwd -P)/$FILE"

    mkdir "$DIR" && cd "$DIR"

    case "$FILE" in
        *.tar.bz2) tar xvjf "$FILE" ;;
        *.tar.gz) tar xvzf "$FILE" ;;
        *.tar.xz) tar xvJf "$FILE" ;;
        *.lzma) unlzma "$FILE" ;;
        *.bz2) bunzip2 "$FILE" ;;
        *.rar) unrar x -ad "$FILE" ;;
        *.gz) gunzip "$FILE" ;;
        *.tar) tar xvf "$FILE" ;;
        *.tbz2) tar xvjf "$FILE" ;;
        *.tgz) tar xvzf "$FILE" ;;
        *.zip) unzip "$FILE" ;;
        *.Z) uncompress "$FILE" ;;
        *.7z) 7z x "$FILE" ;;
        *.xz) unxz "$FILE" ;;
        *.exe) cabextract "$FILE" ;;
        *) echo "extract: '$f' - unknown archive method" ;;
    esac

    if [[ "$(ls -l "$DIR" | wc -l)" == 2 ]]; then
        mv "$DIR"/* "$DIR"/../
        rmdir "$DIR"
    fi
done
